name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    
  macos:  
    runs-on: macos-latest
    env:
      PACKAGENAME: ehentai_py37_macos_x64
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==4.6
        pip install PySide6==6.1.3
        pip install websocket-client==0.59.0
        pip install requests==2.26.0
        pip install urllib3==1.25.11
        pip install pillow==8.3.2
        pip install bs4==0.0.1
        pip install lxml==4.6.4
        pip install pycryptodomex==3.12.0
        pip install Pysocks==1.7.1
        pip install natsort==8.2.0
        pip install https://github.com/tonquer/waifu2x-vulkan/releases/download/v1.1.6/waifu2x_vulkan-1.1.6-cp37-cp37m-macosx_10_15_x86_64.whl
        brew install create-dmg
    - name: Build
      run: |
        cd src
        cp ../res/icon/Icon.icns ./
        pyinstaller --clean --onedir --name EHentai \
            --hidden-import waifu2x_vulkan --hidden-import PySide6 --hidden-import requests \
            --hidden-import urllib3 --hidden-import websocket-client --hidden-import pillow \
            --hidden-import config \
            --hidden-import component \
            --hidden-import server \
            --hidden-import task \
            --hidden-import tools \
            --hidden-import view \
            --strip --windowed -i Icon.icns \
            start.py
        rm -rf dist/EHentai
        cp Icon.icns dist/
        ln -s /Applications/   dist/Applications
        create-dmg --volname "EHentai" --volicon "Icon.icns" --icon "Icon.icns" 200 190 \
            --hide-extension "Icon.icns" ${{ env.PACKAGENAME }}.dmg dist/
        zip -9 ehentai.zip ${{ env.PACKAGENAME }}.dmg
        mv ${{ env.PACKAGENAME }}.dmg ..
        mv ehentai.zip ..
        cd ..
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}
        retention-days: 7



  windows:
    runs-on: windows-latest
    env:
      PACKAGENAME: ehentai_py37_windows_x64
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==4.8
        pip install pywin32==302
        pip install -r src\requirements.txt
    - name: Build
      run: |
        cd src
        cp ..\res\icon\icon.ico .\

        pyinstaller -F -w -i icon.ico start.py
        mv dist ehentai
        cp ..\LICENSE ehentai\
        cp ..\CHANGELOG ehentai\
        cd ..
        mkdir ${{ env.PACKAGENAME }}
        mv src\ehentai ${{ env.PACKAGENAME }}
        7z a -r "$($Env:PACKAGENAME + '.zip')" "ehentai"
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}
        retention-days: 7
        
  windows7:
    runs-on: windows-latest
    env:
      PACKAGENAME: ehentai_py37_windows7_x64
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==4.6
        pip install pywin32==302
        pip install PySide6==6.1.3
        pip install requests==2.26.0
        pip install urllib3==1.25.11
        pip install pillow==8.3.2
        pip install Pysocks==1.7.1
        pip install bs4==0.0.1
        pip install lxml==4.6.4
        pip install natsort==8.2.0
        pip install pycryptodomex==3.12.0
        pip install waifu2x-vulkan==1.1.6
    - name: Build
      run: |
        cd src
        cp ..\res\icon\icon.ico .\
        pyinstaller -F -w -i icon.ico start.py
        mv dist ehentai
        cp ..\LICENSE ehentai\
        cp ..\CHANGELOG ehentai\
        cd ..
        mkdir ${{ env.PACKAGENAME }}
        mv src\ehentai ${{ env.PACKAGENAME }}
        7z a -r "$($Env:PACKAGENAME + '.zip')" "ehentai"
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}
        retention-days: 7
